/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/rubiks_cube.glb 
Author: DatSketch (https://sketchfab.com/DatSketch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/rubiks-cube-eaba6bf1c7da497f926852006c7bd855
Title: Rubik's Cube
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

 const  RubiksCube = (props) => {
  const { nodes, materials } = useGLTF('/rubiks_cube.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={201.057}>
        <group scale={0.209}>
          <group scale={2.383}>
            <mesh geometry={nodes['1_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['1_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['1_Yellow_0'].geometry} material={materials.Yellow} />
            <mesh geometry={nodes['1_Orange_0'].geometry} material={materials.Orange} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['2_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['2_Yellow_0'].geometry} material={materials.Yellow} />
            <mesh geometry={nodes['2_Orange_0'].geometry} material={materials.Orange} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['3_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['3_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['3_Orange_0'].geometry} material={materials.Orange} />
            <mesh geometry={nodes['3_Yellow_0'].geometry} material={materials.Yellow} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['4_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['4_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['4_Yellow_0'].geometry} material={materials.Yellow} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['5_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['5_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['5_Yellow_0'].geometry} material={materials.Yellow} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['6_Red_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['6_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['6_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['6_Yellow_0'].geometry} material={materials.Yellow} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['7_Red_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['7_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['7_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['7_Yellow_0'].geometry} material={materials.Yellow} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['8_Yellow_0'].geometry} material={materials.Yellow} />
            <mesh geometry={nodes['8_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['8_Red_0'].geometry} material={materials.material} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['9_Yellow_0'].geometry} material={materials.Yellow} />
            <mesh geometry={nodes['9_Black_0'].geometry} material={materials.Black} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['10_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['10_White_0'].geometry} material={materials.White} />
            <mesh geometry={nodes['10_Red_0'].geometry} material={materials.material} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['11_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['11_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['11_White_0'].geometry} material={materials.White} />
            <mesh geometry={nodes['11_Red_0'].geometry} material={materials.material} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['12_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['12_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['12_White_0'].geometry} material={materials.White} />
            <mesh geometry={nodes['12_Orange_0'].geometry} material={materials.Orange} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['13_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['13_White_0'].geometry} material={materials.White} />
            <mesh geometry={nodes['13_Orange_0'].geometry} material={materials.Orange} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['14_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['14_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['14_Orange_0'].geometry} material={materials.Orange} />
            <mesh geometry={nodes['14_White_0'].geometry} material={materials.White} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['15_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['15_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['15_White_0'].geometry} material={materials.White} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['16_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['16_Blue_0'].geometry} material={materials.Blue} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['17_Red_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['17_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['17_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['17_White_0'].geometry} material={materials.White} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['18_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['18_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['18_White_0'].geometry} material={materials.White} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['19_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['19_White_0'].geometry} material={materials.White} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['20_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['20_Red_0'].geometry} material={materials.material} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['21_Green_0'].geometry} material={materials.Green} />
            <mesh geometry={nodes['21_Black_0'].geometry} material={materials.Black} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['22_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['22_Orange_0'].geometry} material={materials.Orange} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['23_Red_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['23_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['23_Blue_0'].geometry} material={materials.Blue} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['24_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['24_Blue_0'].geometry} material={materials.Blue} />
            <mesh geometry={nodes['24_Orange_0'].geometry} material={materials.Orange} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['25_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['25_Red_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['25_Green_0'].geometry} material={materials.Green} />
          </group>
          <group scale={2.383}>
            <mesh geometry={nodes['26_Orange_0'].geometry} material={materials.Orange} />
            <mesh geometry={nodes['26_Black_0'].geometry} material={materials.Black} />
            <mesh geometry={nodes['26_Green_0'].geometry} material={materials.Green} />
          </group>
          <mesh geometry={nodes.Rubik_Material001_0.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
  )
}
export default RubiksCube;

useGLTF.preload('/rubiks_cube.glb')
